import {getPrompt} from "../prompting/promptGenerator.js";
import traverse from "@babel/traverse";
import parser from "@babel/parser";

export default class Triage {

   /**
    * This function performs triage on a given exploit and vulnerability.
    * We use heuristics to filter out false positives that are often generated by the model.
    *
    * @param {RuntimeInfo} runtimeInfo - Information about the runtime environment.
    * @param {NpmPackage} npmPackage - The npm package that the exploit is targeting.
    * @param {string} exploitCode - The exploit to be triaged.
    * @param {VulnerabilityType} vulnerabilityType - The type of the vulnerability.
    * @param {string} vulnerabilityDescription - A description of the vulnerability.
    * @param {Model} model - The model used to query for false positives.
    */
   constructor(runtimeInfo, exploitCode, npmPackage, vulnerabilityType, vulnerabilityDescription, model) {
      this.runtimeInfo = runtimeInfo;
      this.exploitCode = exploitCode;
      this.npmPackage = npmPackage;
      this.vulnerabilityType = vulnerabilityType;
      this.vulnerabilityDescription = vulnerabilityDescription;
      this.model = model;
   }

   /**
    * @returns {Promise<boolean>} - Returns true if the exploit is a true positive, otherwise false.
    */
   async isTruePositive() {
      if (this.runtimeInfo.confirmedFromSource && !this.runtimeInfo.confirmed) {
         throw new Error("Illegal state.")
      }
      if (this.checkFalsePositiveHeuristics()) {
         return false;
      }
      // This can still cause false negatives, however they are rare
      if (this.runtimeInfo.confirmedFromSource) {
         return true;
      }
      const prompt = getPrompt("detectFalsePositive", {
         vulnerabilityType: this.vulnerabilityType,
         exploit: this.exploitCode,
         vulnerabilityDescription: this.vulnerabilityDescription,
         package: this.npmPackage
      });
      const response = await this.model.queryOne(prompt);
      return response.split("\n")[0].toLowerCase().trim() === "true positive";
   }

   checkFalsePositivePP() {
      let falsePositive = false;
      traverse.default(this.parsed, {
         AssignmentExpression(path) {
            try {
               const left = path.node.left;
               if (
                  left.type === "MemberExpression" &&
                  left.property.name === "exploited" &&
                  ["__proto__", "prototype"].includes(left.object.property.name)
               ) {
                  falsePositive = true;
                  path.stop();
               }
            } catch (e) {
            }
         }
      });

      return falsePositive;
   }

   /**
    * Parses the exploit code using Babel parser.
    *
    * @returns {ParseResult<File>}
    */
   get parsed() {
      return parser.parse(this.exploitCode, {
         sourceType: "module",
         plugins: ["jsx"]
      });
   }

   checkFalsePositiveCodeInjection() {
      let falsePositive = false;
      traverse.default(this.parsed, {
         CallExpression(path) {
            const callee = path.node.callee;
            if (
               callee.type === "MemberExpression" &&
               callee.object.name === "process" &&
               callee.property.name === "seteuid"
            ) {
               falsePositive = true;
            }
         }
      });
      return falsePositive;
   }

   /**
    * This function checks heuristics for a given exploit and vulnerability type.
    * It uses specific patterns to identify potential prototype pollution exploits.
    *
    * @returns {boolean} - Returns true if the exploit is a false positive, otherwise false.
    */
   checkFalsePositiveHeuristics() {
      try {
         switch (this.vulnerabilityType.label) {
            case "prototype-pollution":
               return this.checkFalsePositivePP();
            case "code-injection":
               return this.checkFalsePositiveCodeInjection();
         }
      } catch (e) {
         console.error(e);
      }
      return false;
   }

}

